# Generated by Django 3.2.3 on 2021-06-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slugs',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
